version: 2.1
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install Rust
          command: "curl https://sh.rustup.rs -sSf | sh -s -- -y"
      - run:
          name: Install WASM Pack
          command: "source $HOME/.cargo/env && curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -y"
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache2-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache2-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: bootstrap
          command: npm run bootstrap
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
