[package]
name = "paperclip"
version = "0.1.0"
build = "build.rs"
authors = ["Craig Condon <craig.j.condon@gmail.com>"]
edition = "2018"

[build-dependencies]
neon-build = "0.3.1"

[dependencies]
matches = "0.1.8"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = { version = "1.0.44" }
neon = "0.3.3"
neon-serde = "0.3.0"
crc = "1.8.1"
jsonrpc-core = "14.0.5"
jsonrpc-tcp-server = "14.0.5"
reqwest = "0.10.1"
futures = "0.3.1"
curl = "0.4.25"
path_abs = "0.5.0"
regex = "1.3.4"

